# Generated by Django 4.2.3 on 2023-07-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                ("image", models.ImageField(upload_to="", verbose_name="Imagen")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "articulo",
                "verbose_name_plural": "articulos",
                "ordering": ["-created"],
            },
        ),
    ]
